#!/usr/bin/env bash
# After a new migration file is created, reminds Claude to review it
# before applying — especially important for geometry columns and GIST indexes.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ "$FILE_PATH" == *"/backend/alembic/versions/"* ]]; then
  echo "New migration file created. Review it before running 'alembic upgrade head':"
  echo "  - down_revision points to the correct previous migration"
  echo "  - upgrade() and downgrade() are both correct and complete"
  echo "  - Geometry columns use raw op.execute() DDL, not autogenerated type mappings"
  echo "  - Spatial indexes use USING GIST, not the default B-tree"
fi

exit 0
