// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AnalyseFootprintAnalysePostData, AnalyseFootprintAnalysePostErrors, AnalyseFootprintAnalysePostResponses, HealthHealthGetData, HealthHealthGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Analyse
 */
export const analyseFootprintAnalysePost = <ThrowOnError extends boolean = false>(options: Options<AnalyseFootprintAnalysePostData, ThrowOnError>) => (options.client ?? client).post<AnalyseFootprintAnalysePostResponses, AnalyseFootprintAnalysePostErrors, ThrowOnError>({
    url: '/footprint/analyse',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
