// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnalyseRequest
 */
export type AnalyseRequest = {
    /**
     * Geometry
     */
    geometry: ({
        type: 'Point';
    } & PointGeometry) | ({
        type: 'Polygon';
    } & PolygonGeometry);
    /**
     * Buffer Km
     */
    buffer_km?: number | null;
};

/**
 * AnalyseResponse
 */
export type AnalyseResponse = {
    /**
     * Area Ha
     */
    area_ha: number;
    /**
     * Land Cover
     */
    land_cover: Array<LandCoverItem>;
    deforestation_alerts: DeforestationAlerts;
    /**
     * Centroid
     */
    centroid: Array<number>;
    /**
     * Alerts Live
     */
    alerts_live: boolean;
    /**
     * Alerts Fetched At
     */
    alerts_fetched_at: string;
};

/**
 * ConfidenceBreakdown
 */
export type ConfidenceBreakdown = {
    /**
     * Level
     */
    level: string;
    /**
     * Count
     */
    count: number;
    /**
     * Area Ha
     */
    area_ha: number;
};

/**
 * YearlyAlerts
 */
export type YearlyAlerts = {
    /**
     * Year
     */
    year: number;
    /**
     * Count
     */
    count: number;
    /**
     * Area Ha
     */
    area_ha: number;
};

/**
 * DeforestationAlerts
 */
export type DeforestationAlerts = {
    /**
     * Count
     */
    count: number;
    /**
     * Area Ha
     */
    area_ha: number;
    /**
     * Period
     */
    period: string;
    /**
     * By Confidence
     */
    by_confidence: Array<ConfidenceBreakdown>;
    /**
     * By Year
     */
    by_year: Array<YearlyAlerts>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LandCoverItem
 */
export type LandCoverItem = {
    /**
     * Type
     */
    type: string;
    /**
     * Percentage
     */
    percentage: number;
};

/**
 * PointGeometry
 */
export type PointGeometry = {
    /**
     * Type
     */
    type: 'Point';
    /**
     * Coordinates
     */
    coordinates: Array<number>;
};

/**
 * PolygonGeometry
 */
export type PolygonGeometry = {
    /**
     * Type
     */
    type: 'Polygon';
    /**
     * Coordinates
     */
    coordinates: Array<Array<Array<number>>>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type AnalyseFootprintAnalysePostData = {
    body: AnalyseRequest;
    path?: never;
    query?: never;
    url: '/footprint/analyse';
};

export type AnalyseFootprintAnalysePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyseFootprintAnalysePostError = AnalyseFootprintAnalysePostErrors[keyof AnalyseFootprintAnalysePostErrors];

export type AnalyseFootprintAnalysePostResponses = {
    /**
     * Successful Response
     */
    200: AnalyseResponse;
};

export type AnalyseFootprintAnalysePostResponse = AnalyseFootprintAnalysePostResponses[keyof AnalyseFootprintAnalysePostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];
